# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'npm'
    labels: ['dependencies']
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dependencies:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'npm'
    labels: ['dependencies', 'website']
    directory: './website'
    schedule:
      interval: 'weekly'
    groups:
      dependencies:
        update-types:
          - 'minor'
          - 'patch'
